# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=220)),
                ('project_description', models.TextField()),
                ('project_text', models.TextField()),
                ('project_main_image', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
