# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170117_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio',
            field=models.TextField(default='image.png'),
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
